name: Publish to NPM

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Update version from release
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          VERSION=${RELEASE_TAG#v}
          npm version $VERSION --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 